# -*- coding: utf-8 -*-
"""RunCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLEgBTblRYVP6-RfONY5ByT6jOCd_T2_
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/LG_AIMERS
!ls

!pip install --upgrade pip
!pip install pandas numpy scikit-learn pycaret[full] category_encoders mlflow plotly

!python pregnancy_success.py \
  --train_file train.csv \
  --test_df test.csv \
  --strategy "baseline + 변수 삭제 + 일부 타깃 인코딩 + 배란 유도 유형 + 결측치 -1" \
  --data_loader_strategy cleaning8 \
  --labeling_strategy labeling6 \
  --imputation_strategy basic4 \
  --feature_engineering_strategy fe9 \
  --sampling_strategy sampling_dummy \
  --modeling_strategy ensemble_split_majority2 \
  --test_size 0.1 \
  --n_splits 3 \
  --experiment_log experiment_results.csv \
  --feature_importance \
  --model_path models/ensemble \
  --feature_path features.csv

!tail -n 50 nohup19.out
!head experiment_results.csv

